protected/controllers/ProjectdetailController.php
<?php
/**
 * The followings are the available model relations:
 * @property Project $project
 */
class ProjectdetailController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			//'postOnly + delete', // we only allow deletion via POST request
			// 'rights',
			);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('index','view','my','juiautocomplete','removetask','starttask','status'),
				'users'=>array('@'),
				),
			array('allow',
				'actions'=>array('create','update','delete','admin','index','view','my'),
				'users'=>array('@'),
				'expression'=>'Yii::app()->user->record->level==1',
				),
			array('deny',
				'users'=>array('*'),
				),
			);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{


		$this->render('view',array(
			'model'=>$this->loadModel($id),
			));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate($projectid)
	{
		$model=new Projectdetail;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Projectdetail']))
		{
			$model->attributes=$_POST['Projectdetail'];
			$model->id_project = $projectid;
			if($model->save())
				$this->redirect(array('project/view','id'=>$model->id_project));
		}

		$this->render('create',array(
			'model'=>$model,
			));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Projectdetail']))
		{
			$model->attributes=$_POST['Projectdetail'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id_projectdetail));
		}

		$this->render('update',array(
			'model'=>$model,
			));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Projectdetail');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			));
	}

	public function actionMy()
	{
		$dataProvider = new CActiveDataProvider('Projectdetail', array(
			'criteria' => array(
				'condition'=>'member = "' . YII::app()->user->record->username . '"'
				)
			));

		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			));
	}		

	public function actionTodo()
	{
		$dataProvider = new CActiveDataProvider('Projectdetail', array(
			'criteria' => array(
				'condition'=>'status=0 And member = "' . YII::app()->user->record->username . '"'
				)
			));

		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			));
	}		


	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Projectdetail('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Projectdetail']))
			$model->attributes=$_GET['Projectdetail'];

		$this->render('admin',array(
			'model'=>$model,
			));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Projectdetail the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Projectdetail::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Projectdetail $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='projectdetail-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	public function actionstatus($id,$id_project)
	{
		$model= $this->loadModel($id);
		if($model != null)
		{
			$model->status_update = date("Y-m-d H:i:s");
			$model->status = 1;		
			$model->save();
			if($model->save()){
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('project/view','id'=>$id_project));
			}
		}
		else{
			$this->actionIndex();
		}
	}

	public function actionstart($id,$id_project)
	{
		$model= $this->loadModel($id);
		if($model != null)
		{
			$model->status_update = NULL;
			$model->status = 0;		
			$model->save();

			if($model->save()){
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('project/view','id'=>$id_project));
			}
		}
		else{
			$this->actionIndex();
		}
	}

	public function actionstarttask($id,$id_project)
	{
		$model= $this->loadModel($id);
		if($model != null)
		{
			$model->job_date = date("Y-m-d h:i:s");
			$model->save();
			if($model->save()){
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('project/view','id'=>$id_project));
			}
		}
		else{
			$this->actionIndex();
		}
	}

	public function actionRemoveTask($id)
	{
		$model=$this->loadModel($id);
		$model->delete();
		$this->redirect(Yii::app()->user->returnUrl);
	}	

	public function actionJuiAutoComplete($term) {
		$criteria = new CDbCriteria;
		// $criteria->compare('fullname', $term, true);
		$criteria->compare('username', $term, true);
		// $criteria->compare('email', $term, true);
		$model = Useraccounts::model()->findAll($criteria);

		foreach ($model as $value) {
			$array[] = array(
				'value' => ($value->fullname . ' - ' . $value->email),  
				'label' => ($value->fullname . ' - ' . $value->email),
				'fullname'=>$value->fullname,
				'username'=>$value->username,  
				'email'=>$value->email, 
				'id_user'=>$value->id_user,  
				);
		}

		echo CJSON::encode($array);
		Yii::app()->end();
	}

	

}

protected/controllers/TasksController.php
<?php

class TasksController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			// 'postOnly + delete', // we only allow deletion via POST request
			);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('index','view','update'),
				'users'=>array('@'),
				),
			array('allow',
				'actions'=>array('create','update','delete','admin','index','view'),
				'users'=>array('@'),
				'expression'=>'Yii::app()->user->record->level==1',
				),
			array('deny',
				'actions'=>array('create','update','delete','admin','index','view'),
				'users'=>array('*'),
				),
			);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
			));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate($projectdetail,$project,$job)
	{
		$model=new Tasks('create');

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Tasks']))
		{
			$model->attributes=$_POST['Tasks'];
			$model->id_projectdetail = $projectdetail;
			$model->id_project = $project;
			$model->task = $job;
			$tmp;
			if(strlen(trim(CUploadedFile::getInstance($model,'file'))) > 0) 
			{ 
				$tmp=CUploadedFile::getInstance($model,'file'); 
				$model->file=YII::app()->user->name.'-'.$model->task.'.'.$tmp->extensionName; 
			}	

			if($model->save())
				if(strlen(trim($model->file)) > 0) 
					$tmp->saveAs(Yii::getPathOfAlias('webroot').'/dokumen/file/'.$model->file);
				$this->redirect(array('view','id'=>$model->id_task));
			}

			$this->render('create',array(
				'model'=>$model,
				));
		}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id,'update');

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Tasks']))
		{
			$model->attributes=$_POST['Tasks'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id_task));
		}

		$this->render('update',array(
			'model'=>$model,
			));
	}

	public function actionReport($id)
	{
		$model=$this->loadModel($id,'update');

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Tasks']))
		{
			$model->attributes=$_POST['Tasks'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id_task));
		}

		$this->render('report',array(
			'model'=>$model,
			));
	}	

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$users=$this->loadModel($id);
		Projectdetail::model()->deleteAllByAttributes(array('member'=>$users->username));
		Tasks::model()->deleteAllByAttributes(array('name'=>$users->username));
		Invoice::model()->deleteAllByAttributes(array('id_user'=>$users->id_user));
		Groups::model()->deleteAllByAttributes(array('id_user'=>$users->id_user));
		$users->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Tasks');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			));
	}

	/**
	 * Lists My Tasks.
	 */
	public function actionMy()
	{
		$dataProvider = new CActiveDataProvider('Tasks', array(
			'criteria' => array(
				'condition'=>'name="' . YII::app()->user->record->username . '"'
				)
			));

		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			));
	}	

	/**
	 * Lists Todo Tasks.
	 */
	public function actionToDo()
	{
		$dataProvider = new CActiveDataProvider('Tasks', array(
			'criteria' => array(
				'condition'=>'status=0 And name="' . YII::app()->user->record->username . '"'
				)
			));
		
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			));
	}	


	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Tasks('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Tasks']))
			$model->attributes=$_GET['Tasks'];

		$this->render('admin',array(
			'model'=>$model,
			));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Tasks the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Tasks::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Tasks $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='tasks-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	public function actionStart($id)
	{
		$model= $this->loadModel($id,'start');
		if($model != null)
		{
			$model->status = 0;		
			$model->save();
			if($model->save()){
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
			}
		}
		else{
			$this->actionIndex();
		}
	}


	public function actionFinish($id)
	{
		$model= $this->loadModel($id,'finish');
		if($model != null)
		{
			$model->status = 1;	
			$model->save();
			if($model->save()){
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
			}
		}
		else{
			$this->actionIndex();
		}
	}	

}

protected/views/projectdetail/_form.php
<?php
/* @var $this ProjectdetailController */
/* @var $model Projectdetail */
/* @var $form CActiveForm */
?>

<div class="form-normal form-horizontal clearfix">
	<div class="col-lg-9 col-md-10"> 

		<?php $form=$this->beginWidget('CActiveForm', array(
			'id'=>'useraccounts-form',
			'enableAjaxValidation'=>false,
			'enableClientValidation'=>true,
			'clientOptions'=>array('validateOnSubmit'=>true),
			'htmlOptions' => array('enctype' => 'multipart/form-data','autocomplete'=>'off'),
			)); ?>

			<?php echo $form->errorSummary(array_merge(array($model)), null, null, array('class' => 'alert alert-warning')); ?>

			<div class="form-group">

				<div class="col-sm-4 control-label">
				</div>   

				<div class="col-sm-8">
					
					<div class="input-group">
						<div class="input-group-addon">
							<i class="fa fa-search"></i>
						</div>
						<?php 
						$this->widget('zii.widgets.jui.CJuiAutoComplete', 
							array( 'name'=>'search', 
								'source'=>$this->createUrl('Projectdetail/JuiAutoComplete'), 
								'options'=>array( 
									'showAnim'=>'fold', 
									'select' => 'js:function(event, ui) {
										$("#Projectdetail_member").val(ui.item.username);
										return false;
									}'
									), 
								'htmlOptions'=>array(
									'class'=>'form-control',
									'placeholder'=>'Search Member'
									),
								)); 
								?>
							</div>

						</div>

					</div>

					<div class="form-group">

						<div class="col-sm-4 control-label">
							<?php echo $form->labelEx($model,'member'); ?>
						</div>   

						<div class="col-sm-8">
							<?php echo $form->error($model,'member'); ?>
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-user"></i>
								</div>
								<?php echo $form->textField($model,'member',array('class'=>'form-control','placeholder'=>'Member','readonly'=>true)); ?>
							</div>
						</div>

					</div>  

					<div class="form-group">

						<div class="col-sm-4 control-label">
							<?php echo $form->labelEx($model,'job'); ?>
						</div>   

						<div class="col-sm-8">
							<?php echo $form->error($model,'job'); ?>
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-tasks"></i>
								</div>
								<?php echo $form->textField($model,'job',array('class'=>'form-control','placeholder'=>'Job')); ?>
							</div>
						</div>

					</div>  												

					<div class="form-group">
						<div class="row">	
							<div class="col-sm-4 control-label">
								<?php echo $form->labelEx($model,'status'); ?>
							</div>   

							<div class="col-sm-8">
								<?php echo $form->error($model,'status'); ?>
								<?php
								echo $form->radioButtonList($model,'status',
									array('0'=>'Start','1'=>'Done'),
									array(
										'template'=>'{input}{label}',
										'separator'=>'',
										'labelOptions'=>array(
											'style'=>'padding-right:20px;margin-left:15px'),

										)                              
									);
									?>

								</div>
							</div>
						</div>

						<div class="form-group">
							<?php echo CHtml::submitButton($model->isNewRecord ? 'Assign' : 'Edit', array('class' => 'btn btn-success btn-flat pull-right', 'style'=>'margin-right: 15px;')); ?>
						</div>

						<?php $this->endWidget(); ?>


					</div>
				</div>

protected/views/projectdetail/_search.php
<?php
/* @var $this ProjectdetailController */
/* @var $model Projectdetail */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id_projectdetail'); ?>
		<?php echo $form->textField($model,'id_projectdetail'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'member'); ?>
		<?php echo $form->textField($model,'member',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'job'); ?>
		<?php echo $form->textField($model,'job',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'status'); ?>
		<?php echo $form->textField($model,'status'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'id_project'); ?>
		<?php echo $form->textField($model,'id_project'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/projectdetail/_view.php
<?php
/* @var $this ProjectdetailController */
/* @var $data Projectdetail */

?>

<div class="box box-<?PHP if($data->status==0){	echo "warning";}else{echo "success";}?>">
<div class="box-header">
	<i class="ion ion-clipboard"></i>
	<h3 class="box-title">
		Task <b><?php echo CHtml::link(CHtml::encode($data->member . " - " . $data->job), array('view', 'id'=>$data->id_projectdetail)); ?></b>
	</h3>
	<div class="box-tools pull-right" data-toggle="tooltip" title="" data-original-title="Status Task">
		<?PHP if($data->status == 0){ ?>
		<small class="label label-warning"><i class="fa fa-clock-o"></i> 
			<?PHP echo $data->status == 0 ? "Start" : "Done"; ?>
		</small>
		<?php }else{ ?>
		<small class="label label-success"><i class="fa fa-clock-o"></i> 
			<?PHP echo $data->status == 0 ? "Start" : "Done"; ?>
		</small>
		<?php } ?>
	</div>
</div>
	</div><!-- /.box-header -->

protected/views/projectdetail/admin.php
<?php
/* @var $this ProjectdetailController */
/* @var $model Projectdetail */

$this->breadcrumbs=array(
	'Projectdetails'=>array('index'),
	'Manage',
	);

$this->pageTitle='Manage Project Detail';
?>

<?php echo CHtml::link('List',
	array('index'),
	array('class' => 'btn btn-success btn-flat'));
	?>

	<?php $this->widget('zii.widgets.grid.CGridView', array(
		'id'=>'projectdetail-grid',
		'dataProvider'=>$model->search(),
		'filter'=>$model,
		'itemsCssClass' => 'table-responsive table table-striped table-hover table-vcenter',
		'columns'=>array(

			array(
				'header'=>'No',
				'value'=>'$this->grid->dataProvider->pagination->currentPage*$this->grid->dataProvider->pagination->pageSize + $row+1',
				'htmlOptions'=>array('width'=>'10px', 
					'style' => 'text-align: center;')),

			'member',
			'job',
			array(    
				'name'=>'status',
				'type'=>'raw', 
				'filter'=>array('1'=>'Complete','0'=>'On Progress'),
				'value'=>'$data->status == 1 ? "Complete" : "On Progress"',
				'sortable' => TRUE, 
				'htmlOptions'=>array('width'=>'130px', 
					'style' => 'font-weight:700;text-align: left;color:#468847;')),

			'status_update',
			'job_date',
			
			array(
				'header'=>'Action',
				'class'=>'CButtonColumn',
				'htmlOptions'=>array('width'=>'100px', 
					'style' => 'text-align: center;'),
				),
			),
			)); ?>

protected/views/projectdetail/create.php
<?php
/* @var $this ProjectdetailController */
/* @var $model Projectdetail */
$this->pageTitle='Add Job';
?>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/projectdetail/index.php
<?php
/* @var $this ProjectdetailController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Tasks',
	);

$this->pageTitle='Jobs List';

?>

<?php 
if(Yii::app()->user->record->level==1):
	echo CHtml::link('Manage Job',
		array('admin'),
		array('class' => 'btn btn-success btn-flat'));
endif;
?>

<?php echo CHtml::link('My Job',
	array('my'),
	array('class' => 'btn btn-success btn-flat'));
	?>

	<?php echo CHtml::link('Todo List',
		array('todo'),
		array('class' => 'btn btn-success btn-flat'));
		?>

		<?php $this->widget('zii.widgets.CListView', array(
			'dataProvider'=>$dataProvider,
			'itemView'=>'_view',
			)); ?>

protected/views/projectdetail/update.php
<?php
/* @var $this ProjectdetailController */
/* @var $model Projectdetail */
$this->pageTitle='Edit Job';
?>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/projectdetail/view.php
<?php
/* @var $this ProjectdetailController */
/* @var $model Projectdetail */
$this->pageTitle='Detail - '.$model->job;
		$tasks = new CActiveDataProvider('Tasks', array(
			'criteria' => array(
				'condition'=>'id_projectdetail = ' . $model->id_projectdetail
				)
			));
?>

<?php echo CHtml::link('<i class="fa fa-arrow-left"></i>',
	array('project/view', 'id'=>$model->id_project),
	array('class' => 'btn btn-success btn-flat','title'=>'Back to Project'));
	?>


	<?php echo CHtml::link('List',
		array('index'),
		array('class' => 'btn btn-success btn-flat', 'title'=>'List Project Detail'));
		?>

		<?php echo CHtml::link('Manage',
			array('admin'),
			array('class' => 'btn btn-success btn-flat','title'=>'Manage Project Detail'));
			?>

			<?php 
			if(Yii::app()->user->record->level==1):
				echo CHtml::link('Add Task',
					array('tasks/create', 'projectdetail'=>$model->id_projectdetail, 'project'=>$model->id_project, 'job'=>$model->job),
					array('class' => 'btn btn-success btn-flat','title'=>'Add Task'));
					?>	
					<?php echo CHtml::link('Edit', 
						array('update', 'id'=>$model->id_projectdetail,
							), array('class' => 'btn btn-warning btn-flat', 'title'=>'Edit Project Detail'));
							?>

							<?php echo CHtml::link('Delete', 
								array('delete', 'id'=>$model->id_projectdetail,
									),  array('class' => 'btn btn-danger btn-flat', 'title'=>'Hapus Project Detail'));
							endif;
							?>

							<h2 class="header">Project <b><?php echo $model->Project->title; ?></b><span class="header-line"></span></h2>
							<?php $this->widget('zii.widgets.CDetailView', array(
								'data'=>$model,
								'htmlOptions'=>array("class"=>"table"),
								'attributes'=>array(

									array(
										'name'=>'Title',
										'value'=>$model->Project->title,
										),

									array(
										'name'=>'Description',
										'value'=>$model->Project->description,
										),

									array(
										'name'=>'Current Status',
										'value'=>$model->Project->current_status,
										),					

									array(
										'name'=>'Start Date',
										'value'=>$model->Project->start_date,
										),					

									array(
										'name'=>'End Date',
										'value'=>$model->Project->deadline,
										),										

									),
									)); ?>

									<h2 class="header">Detail <b>Job <?php echo $model->job; ?></b><span class="header-line"></span></h2>
									<?php $this->widget('zii.widgets.CDetailView', array(
										'data'=>$model,
										'htmlOptions'=>array("class"=>"table"),
										'attributes'=>array(
											'member',
											'job',

											array(
												'name'=>'status',
												'value'=>$model->status == 0 ? "Start" : "Done",
												),

											'status_update',
											'job_date'
											),
											)); ?>

											<h2 class="header">Sub Tasks <b><?php echo $model->job; ?></b><span class="header-line"></span></h2>
											<?php $this->widget('zii.widgets.grid.CGridView', array(
												'id'=>'tasks-grid',
												'dataProvider'=>$tasks,
												//'filter'=>$tasks,
												'itemsCssClass' => 'table-responsive table table-striped table-hover table-vcenter',
												'columns'=>array(

													array(
														'header'=>'No',
														'value'=>'$this->grid->dataProvider->pagination->currentPage*$this->grid->dataProvider->pagination->pageSize + $row+1',
														'htmlOptions'=>array('width'=>'10px', 
															'style' => 'text-align: center;')),
													'name',
													'description',
													'result',
													array(
														'name'=>'status',
														'value'=>'Tasks::model()->status($data->status)',
														),
													'start_date',
													'end_date',

													array(
														'header'=>'Action',
														'type'=>'raw', 
														'value'=>'CHtml::link("Detail", array("tasks/view", "id"=>$data->id_task))',
														'htmlOptions'=>array('width'=>'0px', 
															'style' => 'text-align: left;')),

													),
													)); ?>

<STYLE>
	th{width:180px;}
</STYLE>